name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the master branch
  pull_request:
    branches:
      - master  # Trigger the workflow on pull requests to master

jobs:
  build:
    runs-on: ubuntu-latest  # This runs the workflow on the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This checks out the code from your repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install the dependencies from requirements.txt

      - name: Run tests
        run: |
          # If you have tests (e.g., using pytest), you can run them here
          # For example: pytest tests/
          echo "No tests to run"  # Replace with your testing command if you have any

      - name: Deploy (optional)
        run: |
          echo "Deploying the app..."  # Add your deployment steps here, e.g., to a server or cloud platform
